/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2019-12-22 08:17:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>VotingOnline</title>\r\n");
      out.write("<!--图标库-->\r\n");
      out.write("<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css'>\r\n");
      out.write("\r\n");
      out.write("<!--响应式框架-->\r\n");
      out.write("<link rel='stylesheet' href='css/bootstrap.min.css'>\r\n");
      out.write("\r\n");
      out.write("<!--主要样式-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\" src=\"https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"card-wrap\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"card border-0 shadow card--welcome is-show\" id=\"welcome\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h2 class=\"card-title\">VOTING ONLINE</h2>\r\n");
      out.write("\t\t\t\t<p>欢迎使用 树莓电子投票系统 </p>\r\n");
      out.write("\t\t\t\t<div class=\"btn-wrap\"><a class=\"btn btn-lg btn-register js-btn\" data-target=\"register\">注册</a><a class=\"btn btn-lg btn-login js-btn\" data-target=\"login\">登录</a></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"card border-0 shadow card--register\" id=\"register\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h2 class=\"card-title\">用户注册</h2>\r\n");
      out.write("\t\t\t\t<p>请输入您的相关信息进行注册</p>\r\n");
      out.write("\t\t\t\t<form action=\"RegisterServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" id=\"L_name\" type=\"text\" name=\"name\"  placeholder=\"用户名\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" id=\"L_username\" type=\"text\" name=\"username\" placeholder=\"账号\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" id=\"L_password\" type=\"password\" name=\"password\" placeholder=\"密码\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-lg\" type=\"button\" onclick=\"rsave()\">注册</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button class=\"btn btn-back js-btn\" data-target=\"welcome\"><i class=\"fas fa-angle-left\"></i></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"card border-0 shadow card--login\" id=\"login\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h2 class=\"card-title\">欢迎登录</h2>\r\n");
      out.write("\t\t\t\t<p>请输入您的账号密码</p>\r\n");
      out.write("\t\t\t\t<form action=\"LoginServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" id=\"L_username1\" type=\"text\" name=\"username\" placeholder=\"账号\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"form-control\" id=\"L_password1\" type=\"password\"  name=\"password\" placeholder=\"密码\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<p><a href=\"#\">忘记密码?</a></p>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-lg\" type=\"button\" onclick=\"save()\">登录</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button class=\"btn btn-back js-btn\" data-target=\"welcome\"><i class=\"fas fa-angle-left\"></i></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("<script src=\"js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tfunction rsave(){\r\n");
      out.write("    \t\t\tvar $password=$('#L_password').val();\r\n");
      out.write("    \t\t\tvar $username=$('#L_username').val();\r\n");
      out.write("    \t\t\tvar $name=$('#L_name').val();\r\n");
      out.write("    \t\t\tif($name == \"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"请输入用户名!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    \t\t\telse if($username == \"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"请输入账号!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t    else if($password == \"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"请输入密码!\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t$.post(\r\n");
      out.write("    \t\t\t\t\"/VotingOnline/RegisterServlet\",\r\n");
      out.write("    \t\t\t\t\"username=\"+$username+\"&password=\"+$password+\"&name=\"+$name,\r\n");
      out.write("    \t\t\t\tfunction(result){\r\n");
      out.write("    \t\t\t\t\tif(result=='success')\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\talert(\"注册成功!\");\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href=\"login.jsp\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\tif(result=='error')\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"用户名重复!\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t},\r\n");
      out.write("    \t\t\t\t\"text\")\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tfunction save(){\r\n");
      out.write("    \t\t\tvar $password=$('#L_password1').val();\r\n");
      out.write("    \t\t\tvar $username=$('#L_username1').val();\r\n");
      out.write("    \t\t\tif($username == \"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"请输入账号!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t    else if($password == \"\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"请输入密码!\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t$.post(\r\n");
      out.write("    \t\t\t\t\"/VotingOnline/LoginServlet\",\r\n");
      out.write("    \t\t\t\t\"username=\"+$username+\"&password=\"+$password,\r\n");
      out.write("    \t\t\t\tfunction(result){\r\n");
      out.write("    \t\t\t\t\tif(result=='success')\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\talert(\"管理员 \"+$username+\" 登录成功!\");\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href=\"backstage.jsp\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\tif(result=='error')\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"用户名或密码错误!\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t},\r\n");
      out.write("    \t\t\t\t\"text\")\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
