/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2019-12-20 13:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userpassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>VotingOnline</title>\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi\" />\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/font.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/xadmin.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./lib/layui/layui.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/xadmin.js\"></script>\r\n");
      out.write("    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://cdn.staticfile.org/html5shiv/r29/html5.min.js\"></script>\r\n");
      out.write("      <script src=\"https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"x-body\">\r\n");
      out.write("        <form class=\"layui-form\" action=\"UserPasswordServlet\" method=\"post\">\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_username\" class=\"layui-form-label\">\r\n");
      out.write("                <span class=\"x-red\">*</span>账号</label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\"  id=\"L_username\" name=\"username\" disabled=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_password\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>原密码\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"password\" id=\"L_password\" name=\"oldpass\" required=\"\" lay-verify=\"required\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_pass\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>新密码\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"password\" id=\"L_pass\" name=\"newpass\" required=\"\" lay-verify=\"pass\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_repass\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>确认密码\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"password\" id=\"L_repass\" name=\"repass\" required=\"\" lay-verify=\"repass\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_repass\" class=\"layui-form-label\">\r\n");
      out.write("              </label>\r\n");
      out.write("              <button  class=\"layui-btn\" type=\"button\" onclick=\"save()\">修改</button>\r\n");
      out.write("          </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tfunction save(){\r\n");
      out.write("    \t\t\tvar $oldpass=$('#L_password').val();\r\n");
      out.write("    \t\t\tvar $newpass=$('#L_pass').val();\r\n");
      out.write("    \t\t\tvar $repass=$('#L_repass').val();\r\n");
      out.write("    \t\t\tvar $username=$('#L_username').val();\r\n");
      out.write("    \t\t\tif($newpass == \"\")\r\n");
      out.write("    \t\t\t\t{\r\n");
      out.write("    \t\t\t\talert(\"请输入新的密码!\");\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\telse if($newpass != $repass)\r\n");
      out.write("    \t\t\t\t{\r\n");
      out.write("    \t\t\t\talert(\"两次密码不一致!\");\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\telse{\r\n");
      out.write("    \t\t\t\t$.post(\r\n");
      out.write("    \t\t\t\t\"/VotingOnline/UserPasswordServlet\",\r\n");
      out.write("    \t\t\t\t\"username=\"+$username+\"&newpass=\"+$newpass+\"&oldpass=\"+$oldpass,\r\n");
      out.write("    \t\t\t\tfunction(result){\r\n");
      out.write("    \t\t\t\t\tif(result=='success')\r\n");
      out.write("    \t\t\t\t\t\t{\r\n");
      out.write("    \t\t\t\t\t\t\talert(\"修改成功!\");\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\tif(result=='error')\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"原密码错误!\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t},\r\n");
      out.write("    \t\t\t\t\"text\")\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
