/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.91
 * Generated at: 2019-12-21 07:54:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cn.edu.fzu.sm.vot.entity.user;
import java.util.*;

public final class userlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>VotingOnline</title>\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi\" />\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/font.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/xadmin.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./lib/layui/layui.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/xadmin.js\"></script>\r\n");
      out.write("    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://cdn.staticfile.org/html5shiv/r29/html5.min.js\"></script>\r\n");
      out.write("      <script src=\"https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"x-nav\">\r\n");
      out.write("      <span class=\"layui-breadcrumb\">\r\n");
      out.write("        <a href=\"\">首页</a>\r\n");
      out.write("        <a href=\"\">用户管理</a>\r\n");
      out.write("        <a>\r\n");
      out.write("          <cite>用户列表</cite></a>\r\n");
      out.write("      </span>\r\n");
      out.write("      <a class=\"layui-btn layui-btn-small\" style=\"line-height:1.6em;margin-top:3px;float:right\" href=\"javascript:location.replace(location.href);\" title=\"刷新\">\r\n");
      out.write("        <i class=\"layui-icon\" style=\"line-height:30px\">ဂ</i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"x-body\">\r\n");
      out.write("      <div class=\"layui-row\">\r\n");
      out.write("        <form class=\"layui-form layui-col-md12 x-so\" action=\"UserListServlet\" method=\"post\">\r\n");
      out.write("          <input type=\"text\" id=\"L_username\" name=\"username\"  placeholder=\"请输入账号\" autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("          <button class=\"layui-btn\"  type=\"submit\" ><i class=\"layui-icon\">&#xe615;</i></button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <xblock>\r\n");
      out.write("        <button class=\"layui-btn\" onclick=\"x_admin_show('添加用户','useradd.jsp',600,400)\"><i class=\"layui-icon\"></i>添加</button>\r\n");
      out.write("      </xblock>\r\n");
      out.write("      <table class=\"layui-table\">\r\n");
      out.write("        <thead>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>\r\n");
      out.write("              <div class=\"layui-unselect header layui-form-checkbox\" lay-skin=\"primary\"><i class=\"layui-icon\">&#xe605;</i></div>\r\n");
      out.write("            </th>\r\n");
      out.write("            <th>ID</th>\r\n");
      out.write("            <th>账号</th>\r\n");
      out.write("            <th>用户名</th>\r\n");
      out.write("            <th>性别</th>\r\n");
      out.write("            <th>联系电话</th>\r\n");
      out.write("            <th>注册时间</th>\r\n");
      out.write("            <th>状态</th>\r\n");
      out.write("            <th>操作</th></tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("        ");
 List<user> list=(List<user>)request.getAttribute("userlist");
        	for(user u:list)
        	{
        
      out.write("\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("              <div class=\"layui-unselect layui-form-checkbox\" lay-skin=\"primary\" data-id='2'><i class=\"layui-icon\">&#xe605;</i></div>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>");
      out.print(u.getId());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(u.getUsername());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(u.getName());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(u.getSex());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(u.getPhone());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(u.getTime());
      out.write("</td>\r\n");
      out.write("            <td class=\"td-status\">\r\n");
      out.write("              <span class=\"layui-btn layui-btn-normal layui-btn-mini\">已启用</span></td>\r\n");
      out.write("            <td class=\"td-manage\">\r\n");
      out.write("              <a onclick=\"member_stop(this,'10001')\" href=\"javascript:;\"  title=\"启用\">\r\n");
      out.write("                <i class=\"layui-icon\">&#xe601;</i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a title=\"编辑\"  onclick=\"x_admin_show('编辑','useredit.jsp?username=");
      out.print(u.getUsername());
      out.write("&name=");
      out.print(u.getName());
      out.write("&sex=");
      out.print(u.getSex());
      out.write("&phone=");
      out.print(u.getPhone());
      out.write("&time=");
      out.print(u.getTime());
      out.write("',600,400)\" href=\"javascript:;\">\r\n");
      out.write("                <i class=\"layui-icon\">&#xe642;</i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a title=\"修改密码\" onclick=\"x_admin_show('修改密码','/VotingOnline/userpassword.jsp?username=");
      out.print(u.getUsername());
      out.write("',600,400)\" href=\"javascript:;\">\r\n");
      out.write("                <i class=\"layui-icon\">&#xe631;</i>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a title=\"删除\" onclick=\"del('");
      out.print(u.getUsername());
      out.write("')\" >\r\n");
      out.write("                <i class=\"layui-icon\">&#xe640;</i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("         ");

         }
         
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("      <div class=\"page\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <a class=\"prev\" href=\"\">&lt;&lt;</a>\r\n");
      out.write("          <span class=\"current\">1</span>\r\n");
      out.write("          <a class=\"next\" href=\"\">&gt;&gt;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("      \r\n");
      out.write("       /*用户-停用*/\r\n");
      out.write("      function member_stop(obj,id){\r\n");
      out.write("          layer.confirm('确认要停用吗？',function(index){\r\n");
      out.write("\r\n");
      out.write("              if($(obj).attr('title')=='启用'){\r\n");
      out.write("\r\n");
      out.write("                //发异步把用户状态进行更改\r\n");
      out.write("                $(obj).attr('title','停用')\r\n");
      out.write("                $(obj).find('i').html('&#xe62f;');\r\n");
      out.write("\r\n");
      out.write("                $(obj).parents(\"tr\").find(\".td-status\").find('span').addClass('layui-btn-disabled').html('已停用');\r\n");
      out.write("                layer.msg('已停用!',{icon: 5,time:1000});\r\n");
      out.write("\r\n");
      out.write("              }else{\r\n");
      out.write("                $(obj).attr('title','启用')\r\n");
      out.write("                $(obj).find('i').html('&#xe601;');\r\n");
      out.write("\r\n");
      out.write("                $(obj).parents(\"tr\").find(\".td-status\").find('span').removeClass('layui-btn-disabled').html('已启用');\r\n");
      out.write("                layer.msg('已启用!',{icon: 5,time:1000});\r\n");
      out.write("              }\r\n");
      out.write("          });\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       /*自己写的功能*/   \r\n");
      out.write("      function del(username){\r\n");
      out.write("  \t\t$.post(\r\n");
      out.write("\t\t\t\t\"/VotingOnline/UserDelServlet\",\r\n");
      out.write("\t\t\t\t\"username=\"+username,\r\n");
      out.write("\t\t\t\tfunction(result){\r\n");
      out.write("\t\t\t\t\tif(result=='success')\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"删除成功!\");\r\n");
      out.write("\t\t\t\t\t\t\twindow.location.href=\"/VotingOnline/UserListServlet\"\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\t\"text\")\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>var _hmt = _hmt || []; (function() {\r\n");
      out.write("        var hm = document.createElement(\"script\");\r\n");
      out.write("        hm.src = \"https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190\";\r\n");
      out.write("        var s = document.getElementsByTagName(\"script\")[0];\r\n");
      out.write("        s.parentNode.insertBefore(hm, s);\r\n");
      out.write("      })();</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
